// Element states at room temperature (20°C/293K)
// S = Solid, L = Liquid, G = Gas
const elementStates = {
    1: "G",   // Hydrogen
    2: "G",   // Helium
    3: "S",   // Lithium
    4: "S",   // Beryllium
    5: "S",   // Boron
    6: "S",   // Carbon
    7: "G",   // Nitrogen
    8: "G",   // Oxygen
    9: "G",   // Fluorine
    10: "G",  // Neon
    11: "S",  // Sodium
    12: "S",  // Magnesium
    13: "S",  // Aluminum
    14: "S",  // Silicon
    15: "S",  // Phosphorus
    16: "S",  // Sulfur
    17: "G",  // Chlorine
    18: "G",  // Argon
    19: "S",  // Potassium
    20: "S",  // Calcium
    21: "S",  // Scandium
    22: "S",  // Titanium
    23: "S",  // Vanadium
    24: "S",  // Chromium
    25: "S",  // Manganese
    26: "S",  // Iron
    27: "S",  // Cobalt
    28: "S",  // Nickel
    29: "S",  // Copper
    30: "S",  // Zinc
    31: "S",  // Gallium
    32: "S",  // Germanium
    33: "S",  // Arsenic
    34: "S",  // Selenium
    35: "L",  // Bromine
    36: "G",  // Krypton
    37: "S",  // Rubidium
    38: "S",  // Strontium
    39: "S",  // Yttrium
    40: "S",  // Zirconium
    41: "S",  // Niobium
    42: "S",  // Molybdenum
    43: "S",  // Technetium
    44: "S",  // Ruthenium
    45: "S",  // Rhodium
    46: "S",  // Palladium
    47: "S",  // Silver
    48: "S",  // Cadmium
    49: "S",  // Indium
    50: "S",  // Tin
    51: "S",  // Antimony
    52: "S",  // Tellurium
    53: "S",  // Iodine
    54: "G",  // Xenon
    55: "S",  // Cesium
    56: "S",  // Barium
    57: "S",  // Lanthanum
    58: "S",  // Cerium
    59: "S",  // Praseodymium
    60: "S",  // Neodymium
    61: "S",  // Promethium
    62: "S",  // Samarium
    63: "S",  // Europium
    64: "S",  // Gadolinium
    65: "S",  // Terbium
    66: "S",  // Dysprosium
    67: "S",  // Holmium
    68: "S",  // Erbium
    69: "S",  // Thulium
    70: "S",  // Ytterbium
    71: "S",  // Lutetium
    72: "S",  // Hafnium
    73: "S",  // Tantalum
    74: "S",  // Tungsten
    75: "S",  // Rhenium
    76: "S",  // Osmium
    77: "S",  // Iridium
    78: "S",  // Platinum
    79: "S",  // Gold
    80: "L",  // Mercury
    81: "S",  // Thallium
    82: "S",  // Lead
    83: "S",  // Bismuth
    84: "S",  // Polonium
    85: "S",  // Astatine
    86: "G",  // Radon
    87: "S",  // Francium
    88: "S",  // Radium
    89: "S",  // Actinium
    90: "S",  // Thorium
    91: "S",  // Protactinium
    92: "S",  // Uranium
    93: "S",  // Neptunium
    94: "S",  // Plutonium
    95: "S",  // Americium
    96: "S",  // Curium
    97: "S",  // Berkelium
    98: "S",  // Californium
    99: "S",  // Einsteinium
    100: "S", // Fermium
    101: "S", // Mendelevium
    102: "S", // Nobelium
    103: "S", // Lawrencium
    104: "S", // Rutherfordium
    105: "S", // Dubnium
    106: "S", // Seaborgium
    107: "S", // Bohrium
    108: "S", // Hassium
    109: "S", // Meitnerium
    110: "S", // Darmstadtium
    111: "S", // Roentgenium
    112: "S", // Copernicium
    113: "S", // Nihonium
    114: "S", // Flerovium
    115: "S", // Moscovium
    116: "S", // Livermorium
    117: "S", // Tennessine
    118: "S"  // Oganesson
};
